### ISSUE TITLE
bannertool and makerom are not compatible with Windows

### ISSUE THREAD

**Issue by flarn2006** [Steveice10/3DSHomebrewTemplate#1]
The binaries for `bannertool` and `makerom` that are included do not work on Windows. Please include Windows binaries.

**EDIT**: Also, first. :trollface:

**Comment by Steveice10** [comment]
Working out some other issues right now, but I'll make sure to include some Windows binaries when I can get around to it.

**Comment by flarn2006** [comment]
Okay, thanks. I can't get bannertool to compile though, so can you please post a Windows binary? (To clarify, I can get it to compile, but it gives me this error message whenever I try to use it with your template makefile:

> The procedure entry point __gxx_personality_v0 could not be located in the dynamic link library d:\Users\Flarn\Desktop\3DS_stuff\WorldOf3DSand\tools\bannertool.exe.

**Comment by Steveice10** [comment]
I added Windows binaries, and the Makefile should automatically detect that you're on Windows and use them. Let me know if it works or not.

**Comment by flarn2006** [comment]
Okay, first off: the makefile doesn't work properly on Windows. I see you're trying to add ".exe" to the end of the variables when it detects you're running Windows, but for some reason it adds a space first, so what it actually does is attempt to load the Linux versions with ".exe" as its first parameter. This code works fine on Windows, and should on Linux as well:

    ifeq ($(OS),Windows_NT)
    	MAKEROM    = $(TOPDIR)/tools/makerom.exe
    	BANNERTOOL = $(TOPDIR)/tools/bannertool.exe
    else
    	MAKEROM    = $(TOPDIR)/tools/makerom
    	BANNERTOOL = $(TOPDIR)/tools/bannertool
    endif

The CIA version works fine, if it's supposed to display a black screen when you run it. (Which usually wouldn't be the case, but given that this is only a template, I wouldn't be at all surprised.) However, when you go to "unwrap" the icon, and also when it's suspended, its name shows up like this:

![WTF](http://i.imgur.com/8Jw9JDQ.jpg)

The .3DS version doesn't work, however. It shows up properly in the Gateway menu (though the ".3ds" extension is visible), and selecting it does cause it to appear as if it is inserted as a cartridge. However, when I attempt to load it, it gives me a black screen saying the game card was removed, and sends me back to sysnand.

Also, why is bannertool.exe 7 megabytes? It just doesn't seem like it would need to be that big.

**Comment by Steveice10** [comment]
The Makefile variable problem is now fixed in the repo.

You are correct in assuming that the black screen is because its a template. I'll add a hello world message in now just to make it clear that it works.

bannertool.exe is probably 7 megabytes because I statically linked the required libraries into it to avoid errors like the one you were having when compiling it.

I have to go out for a bit now, so I'll look into why the .3DS version isn't working and why the text shows up wrong when I get back.

**Comment by Steveice10** [comment]
Actually, the text issue was fairly simple, so it should be fixed now.

**Comment by flarn2006** [comment]
Yep, it was fixed. But I'm still getting the problem where the .3DS doesn't load.

**Comment by Steveice10** [comment]
Can you try this 3DS file and see if it works: https://www.dropbox.com/s/fwl86wyyzw5q5lc/Worldof3DSand.3ds?dl=0

(I don't have a Gateway or anything of that sort to test it with.)

**Comment by flarn2006** [comment]
That works!

**Comment by Steveice10** [comment]
Should be all fixed in the source repo then. Let me know if compiling it yourself works and I'll close the issue.

**Comment by flarn2006** [comment]
It gives me that same error with the broken text when I use the .3DS version and suspend it with Home.

**Comment by Steveice10** [comment]
That's strange... there should be a file named "icon.icn" in the build folder of the project after running make, can you upload and link it here?

**Comment by flarn2006** [comment]
http://www.filedropper.com/showdownload.php/icon_5

Also, I just deleted the folder and redownloaded the ZIP file, so `make clean` wouldn't have been necessary, right?

**Comment by Steveice10** [comment]
Yeah, it shouldn't be a problem then. I just headed off to bed, so I'll make sure to take a look and figure it out as soon as I can tomorrow.

**Comment by Steveice10** [comment]
Hmm... not to sure why that would happen. The icon file looks alright.

For what its worth, I've updated things a bit, so you can try building again and see what happens.

**Comment by flarn2006** [comment]
It's still giving me the same problem with the .3DS file.

**Comment by Steveice10** [comment]
Can you post a screenshot or something of the problem, specifically when using the 3DS version?

**Comment by flarn2006** [comment]
![20150128_205910](https://cloud.githubusercontent.com/assets/687313/5951155/fad34e02-a730-11e4-9b33-94fe867b3942.jpg)

Also, notice that "◙Y: 67" in the corner. That's a bug in the `screen_draw_string` function where `\n` isn't handled properly. Should I create a separate issue for that or is that enough information?

**Comment by Steveice10** [comment]
Does the title show correctly when the icon is selected in the home menu? (If you set the layout to 1 row of icons, it shows a title and author above the selected icon.)

Also, I'll go ahead and fix that newline issue.

**Comment by flarn2006** [comment]
Nope, shows up the same. Also, I edited icon.png, which shows up fine in the Gateway menu, but not on the cartridge image.

**Comment by flarn2006** [comment]
Oh, one more thing you might want to be aware of: I edited AppInfo to say the following:

    APP_TITLE = Bouncing Square
    APP_DESCRIPTION = Title says it all.
    APP_AUTHOR = flarn2006
    APP_PRODUCT_CODE = BouncingSquare
    APP_UNIQUE_ID = 0xF1337

Then when I built and installed the CIA, it didn't show up as an icon in the Home Menu, or in the dev menu. Though if I try to install it again, it says it's already installed.

**Comment by Steveice10** [comment]
There was an issue not too long ago with the icon generation that caused that... is that with the latest commit?

**Comment by flarn2006** [comment]
Well latest as of about a half an hour ago; I see you fixed the newline issue I mentioned but I haven't tested it with that yet.

**Comment by Steveice10** [comment]
Does the CIA version show the title properly?

**Comment by flarn2006** [comment]
Yes, and the icon as well.

**Comment by flarn2006** [comment]
Actually I don't know what I did differently, but I just built a different .3ds and the text worked fine.

[Here's the icon.icn.](http://www.filedropper.com/showdownload.php/icon_1)

**Comment by Steveice10** [comment]
So... everything is good then? Titles and icons are showing up fine on both 3DS and CIA files?

**Comment by flarn2006** [comment]
Well it seems with .3DS it only happens sometimes. It didn't work before, but then it did later.

**Comment by Steveice10** [comment]
Since it seems to be working for you now and it's working fine in my testing, I'll go ahead and close this issue.
