### ISSUE TITLE
Cannot change sound for application

### ISSUE THREAD

**Issue by AtlanticBit** [Steveice10/3DSHomebrewTemplate#2]
When I try I only get a series of beeps(.wav file).

**Comment by Steveice10** [comment]
Putting in a custom WAV file is working fine for me... what WAV file are you supplying it?

**Comment by AtlanticBit** [comment]
A 5/6 second one, but I also tried a 2 second one.

**Comment by Steveice10** [comment]
Could you upload the WAV file in question so I can use it to figure out the problem?

**Comment by AtlanticBit** [comment]
http://ctrepo.brunoturek.com/audio.wav
(my server don't be scared)

**Comment by Steveice10** [comment]
It needs to be ~3 seconds long. That is too long.

**Comment by AtlanticBit** [comment]
the 2 second doesn't work too though

**Comment by Steveice10** [comment]
Upload that one then, please.

**Comment by AtlanticBit** [comment]
oh never mind
